---
# This playbook used to demo OpenStack Juno user, role, image and volume features. 

- hosts: util_container
  user: root
  remote_user: root
  sudo: yes
  roles:
    - create-users-env
    - add-new-vmimage
    - create-log-volume